### ISSUE TITLE
Add CAS authentication (like moocRP)

### ISSUE THREAD

**Issue by zpardos** [CAHLR/course_recommendation_interface#6]
We would like students at Cal to be able to login with their University username/password (called CalNet). This will be particularly useful for maximizing the ease of getting started interacting with the system when we start spreading word of the system to more students in order to gain additional feedback. 

The moocRP code-base includes support for CAS authentication. We should retain the sign-up feature for those outside of the system, and perhaps put the non-CAS alternative login in small print somewhere on the bottom of the screen.

**Comment by yuetianluo** [comment]
add CAS authentication and put the non-CAS alternative login on the bottom of the screen
