### ISSUE TITLE
Add support for logging of user queries

### ISSUE THREAD

**Issue by zpardos** [CAHLR/course_recommendation_interface#7]
We should be logging the queries students are entering into our various analyses. In the example of Analysis 1 (similar courses), we should be logging (1) the course they entered (2) their username (3) a timestamp/date (3) and of course the particular analysis (Analysis 1) - for every analysis they do. When we create future analyses (soon :) those analyses should also log similar information that would allow us to re-create their query.

**Comment by yuetianluo** [comment]
add log file to record sails.log information
