### ISSUE TITLE
Create "investigate course relationships" interface for vector arithmetic

### ISSUE THREAD

**Issue by zpardos** [CAHLR/course_recommendation_interface#8]
This analysis, called "investigate course relationships" should allow the user to enter positive and negative courses and then get the top 10 similar courses to the resultant vector. The user should be able to enter at least up to 3 positive and 3 negative courses. The interface could be as simple as three of the course search box rows under "Positive" and another three under "Negative."

The gensim word2vec api allows for a list of vectors to be provided which represent the added vectors and a list which represent the negated vectors. In the case of King - Man + Woman = Queen, the positive vectors are [King, Woman], and negatives are [Man]. This API likely also allow for only positives or only negatives to be specified.

For the time being this analysis should not be directly linked to in the interface.

**Comment by yuetianluo** [comment]
on the analysis one page add investigate course relationships part
